--DATABASE 
DROP DATABASE QLBANSACH;

CREATE DATABASE QLBANSACH;

USE QLBANSACH;

CREATE TABLE ROLE 
(
    ID INT AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50),
    PRIMARY KEY (ID) 
);

CREATE TABLE USER
(
    USERNAME VARCHAR(30),
    PASSWORD VARCHAR(500),
    USER_ID INT,
    ROLE_ID INT,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE USER_INFOR
(
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(30),
    FULLNAME NVARCHAR(70),
    BIRTHDAY DATETIME,
    PHONE_NUMBER VARCHAR(10),
    MAIL VARCHAR(50),
    ADDRESS NVARCHAR(100),
    CREATE_DATE DATETIME,
    UPDATE_DATE DATETIME,
    PRIMARY KEY(ID)
);

CREATE TABLE AUTHOR
(
    ID INT AUTO_INCREMENT,
    AUTHOR_NAME NVARCHAR(70),
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY
(
    ID INT AUTO_INCREMENT,
    CATEGORY_NAME NVARCHAR(30),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT
(
    ID INT AUTO_INCREMENT,
    PRODUCT_NAME NVARCHAR(100),
    AUTHOR_ID INT,
    CATEGORY_ID INT,
    QUANTITY INT,
    PUBLISHED_DATE DATETIME,
    DESCRIPTION TEXT,
    IMAGE_URL TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE CART
(
    USER_ID INT,
    TOTAL_MONEY INT,
    STATE VARCHAR(30),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE CART_DETAIL 
(
    ID INT AUTO_INCREMENT,
    USER_ID INT,
    PRODUCT_ID INT,
    NUMBER INT,
    PRICE INT,
    PRIMARY KEY (ID)
);

--- ràng buộc
USE QLBANSACH;

ALTER TABLE USER
ADD 
(
    CONSTRAINT FK_USER_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLE(ID),

    CONSTRAINT FK_USER_USER_INFOR
    FOREIGN KEY (USER_ID)
    REFERENCES USER_INFOR(ID)
);

ALTER TABLE USER_INFOR
ADD 
(   
    CONSTRAINT FK_USERNAME_USERNAME
    FOREIGN KEY (USERNAME)
    REFERENCES USER(USERNAME)
);

ALTER TABLE CART
ADD
(
    CONSTRAINT FK_USER_ID_ID
    FOREIGN KEY (USER_ID)
    REFERENCES USER_INFOR(ID)
);

ALTER TABLE CART_DETAIL
ADD
(
    CONSTRAINT FK_USER_ID_USER_ID
    FOREIGN KEY (USER_ID)
    REFERENCES CART(USER_ID),

    CONSTRAINT FK_PRODUCT_ID_ID
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCT(ID)
);

ALTER TABLE PRODUCT
ADD
(
    CONSTRAINT FK_CATEGORY_ID_ID
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY(ID)
);

--- Data mặc định 
INSERT INTO ROLE(ROLE_NAME)
VALUES 
    ('ADMIN'),
    ('USER');

INSERT INTO USER 
VALUES 
    ('ADMIN', '123', NULL, '1');

INSERT INTO USER_INFOR (USERNAME)
VALUES
    ('ADMIN');

---  Stored Procedure
DROP PROCEDURE CREATE_USER

CREATE PROCEDURE CREATE_USER(IN p_USERNAME NVARCHAR(20), IN p_PASSWORD VARCHAR(30), IN p_MAIL VARCHAR(50), OUT p_Message NVARCHAR(255))
BEGIN 
    DECLARE v_Id INT;
    
    IF (FIND_USER(p_USERNAME) IS NOT NULL) THEN
        SET p_Message = 'ĐÃ TỒN TẠI USER';
    ELSE
        INSERT INTO USER (USERNAME, PASSWORD, ROLE_ID)
        VALUES (p_USERNAME, p_PASSWORD, 2);
        
        INSERT INTO USER_INFOR (USERNAME, MAIL, CREATE_DATE, UPDATE_DATE) 
        VALUES (p_USERNAME, p_MAIL, NOW(), NOW());

        SET v_Id = (SELECT ID FROM USER_INFOR WHERE USER_INFOR.USERNAME = p_USERNAME);
        UPDATE USER
        SET USER.USER_ID = v_Id WHERE USER.USERNAME=p_USERNAME;
    
        INSERT INTO CART(USER_ID, TOTAL_MONEY)
        VALUES (v_Id, 0);
        
        SET p_Message = 'TẠO TÀI KHOẢNG THÀNH CÔNG';
    END IF;
    
END;

--CALL CREATE_USER('Minh Quang', '12344', 'huynhminhquang2803@gmail.com', @p_mes) ; SELECT @p_mes;




--- Function
CREATE FUNCTION FIND_USER(Username VARCHAR(30))
RETURNS VARCHAR(30)
DETERMINISTIC
NO SQL
BEGIN 
    DECLARE result VARCHAR(30);
    SET result =  (SELECT USERNAME 
    FROM USER
    WHERE USER.USERNAME = Username);

    RETURN result;
END;


