--DATABASE 
USE MASTER 

CREATE DATABASE QLBANSACH

CREATE TABLE ROLE
(
    ID VARCHAR(3),
    ROLENAME NVARCHAR(15),
    PRIMARY KEY (ID)
)
CREATE TABLE USERS
(
    USERNAME NVARCHAR(15),
    PASSWORDS VARCHAR(20),
    ROLE_ID VARCHAR(3)
    ID VARCHAR(4),
    PRIMARY KEY (USERNAME)
)
CREATE TABLE USERINFOR
(
    ID VARCHAR(4),
    FULL_NAME NVARCHAR(30),
    BIRTHDAY DATETIME,
    PHONE_NUMBER VARCHAR(10),
    MAIL VARCHAR(50),
    ADRS NVARCHAR(100),
    
    CREATE_DAY DATETIME,
    UPDATE_DAY DATETIME,
    PRIMARY KEY(ID)
)

